### GENERAL SETTINGS ###

# Site settings
title: University of Brawijaya Game Laboratory.
description: "University of Brawijaya Game Laboratory."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ubgamelab.org"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: youtube
    url:
  - title: twitter
    url:


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Game Laboratory, 1st Floor Building C
    - Faculty of Computer Science, University of Brawijaya
    - Veteran Road, 8, Malang
    - 65145, East Java
    - Indonesia
email: ubgamelab@gmail.com
tel: +62 0341 577-911


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Eriq Muhammad Adams J.
    position: Head of Laboratory & Research Director
    text: "Research Interest : Game Artificial Intelligence & Mixed Reality"
    img: eriq.jpg
    social:
      - title: envelope #use for email address
        url: mailto:eriq.adams@ub.ac.id
  - name: Issa Arwani
    position: Researcher
    text: "Research Interest : Game Design"
    img: issa.jpg
    social:
      - title: envelope #use for email address
        url: mailto:issa.arwani@ub.ac.id
  - name: Wibisono Sukmo Wardhono
    position: Researcher
    text: "Research Interest : Mixed Reality"
    img: wibi.jpg
    social:
      - title: envelope #use for email address
        url: mailto:wibiwardhono@ub.ac.id
  - name: M. Aminul Akbar
    position: Research Assistant
    text: "Research Interest : Game Artificial Intelligence"
    img: akbar.jpg
    social:
      - title: envelope #use for email address
        url: mailto:muhammad.aminul@ub.ac.id
  - name: Febri Abdullah
    position: Research Assistant
    text: "Research Interest : Game Artificial Intelligence & Mixed Reality"
    img: febri.jpg
    social:
      - title: envelope #use for email address
        url: mailto:febri@ub.ac.id
  - name: Kurnia Prima Putra
    position: Research Assistant
    text: "Research Interest : Interactive Computer Graphics & Mixed Reality"
    img: prima.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kurnia@ub.ac.id
  - name: Aninditya Nugroho
    position: Administrative
    img: didit.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aninditya@ub.ac.id
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "UB GAMELAB is a game research groups @ Faculty of Computer Science, University of Brawijaya"
